language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  postgresql: "9.4"
before_install:
  - psql -c 'create database "copy-test"' -U postgres
  - travis_retry pip install -U pip wheel
install:
  - travis_retry pip install -U .
  - travis_retry pip install -U -r dev-requirements.txt
script:
  - py.test
  - flake8 .
